name = "foodmarket-payroll"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "payroll-db"
database_id = "f8f2e7df-40b0-4577-8e88-c565f08aafb0"
